### ISSUE TITLE
Some of the downloaded AVA-Kinetics cannot be played

### ISSUE THREAD

**Issue by Deep-learning999** [gurkirt/kinetics-download-prep#5]
Some of the downloaded AVA-Kinetics are divided into 7 seconds and 8 seconds, about 10%, why not 6 seconds, and many videos cannot be played, it should be an encoding error
![Screenshot_20210506_090129](https://user-images.githubusercontent.com/64831773/117227566-b22be980-ae49-11eb-9ea5-1f25ff510b57.jpg)

**Comment by gurkirt** [comment]
It is problem with FFmpeg, version or something, you try system ffmpeg or anaconda ffmpeg. To try system ffmpeg use /usr/bin/ffmpeg instead of ffmpeg when defining  ffmpeg related command for system process.

Also, I would suggest downloading the video in a temp file then trim using ffmpeg. 

You need to try all these tricks and download these videos. Then combine these sets of videos into one functional set of videos. 
What I did was to, extract frames, if extracted frames were more than 130 at 30 fps then that mean that is function video. Now only download unfunctional videos by replacing ffmpeg with /usr/bin/ffmpeg at [this line](https://github.com/gurkirt/kinetics-download-prep/blob/main/download.py#L103). Repeat the process by downloading temp file or without downliaind process. After all this I was able to get almost 192K videos from 204K, which were functional.

Sorry, there is no easy fix to this mess.

**Comment by Deep-learning999** [comment]
Okay, I will try it again. Could you share your experience with slowfast training ava_kinetics, such as how to convert the kinetics part into clips and keyframes in ava format

**Comment by gurkirt** [comment]
You would be happy to know that the original dataset is now made available directly by CVDF, see https://github.com/cvdfoundation/kinetics-dataset
